### ISSUE TITLE
Missing solution file for Visual Studio

### ISSUE THREAD

**Issue by Eastrall** [nicolasgere/Vulpix#1]
Hi,

I was reading the sources here on github and I noticed that there is no solution file (.sln) or c# project file (.csproj) for opening the project with Visual Studio.

I assume you developped the first version on a Linux environment right ? I can open a pull request to add a visual studio solution and project file if you want 😄 

Btw, really interesting project !

**Comment by nicolasgere** [comment]
Hi,
yes i use visual studio code for develop it on linux and windows, if you want to modify the project:
- create a directory with app and vulpix
- clone the repository in vulpix folder
- and follow http://forums.dotnetfoundation.org/t/referencing-another-project-in-net-core/1298/2

and the idea of a sln file or csproj could be very nice !

**Comment by Eastrall** [comment]
Solved with PR #2
